declare const APP_DATA_PATH: any;
declare const USER_PROCESSES_PATH: any;
declare const USER_TEMPLATES_PATH: any;
declare const SYSTEM_TEMPLATES_PATH: any;
declare const SYSTEM_GRAPHS_PATH: any;
export { APP_DATA_PATH, USER_PROCESSES_PATH, USER_TEMPLATES_PATH, SYSTEM_TEMPLATES_PATH, SYSTEM_GRAPHS_PATH };
